name: Deploy to npm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      - uses: Github-Actions-Community/merge-release@22d66d3f7750d57b2b8c05db6077205332527df8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: .
          SRC_PACKAGE_DIR: .
