name: Deploy to npm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required to mint token for npm package provenance
      contents: write # Needed to create and write release notes in GitHub release

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"

      - run: |
          git config --global user.email "bot@ci.com"
          git config --global user.name "CI"
          git commit --allow-empty -m "feat(deploy): Release a new version"

      - uses: tobua/release-npm-action@v3
        with:
          MANUAL_TRIGGER: "regular"
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
